# Generated by Django 4.2.28 on 2026-02-17 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g., Cereals, Legumes).', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of the category.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'crop categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='idx_category_name')],
            },
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Common name of the crop.', max_length=100)),
                ('scientific_name', models.CharField(help_text='Scientific (Latin) name of the crop.', max_length=150)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of the crop.')),
                ('growth_duration_days', models.PositiveIntegerField(help_text='Number of days from planting to harvest.')),
                ('water_requirements', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], help_text='Water requirement level: low, medium, or high.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Category this crop belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='crops.cropcategory')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='idx_crop_name'), models.Index(fields=['scientific_name'], name='idx_crop_sci_name'), models.Index(fields=['category'], name='idx_crop_category')],
            },
        ),
    ]
