# Generated by Django 4.2.28 on 2026-02-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='growth_duration_days',
            field=models.IntegerField(help_text='Number of days from planting to harvest.'),
        ),
    ]
